In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv(r"C:\Users\Zulkarnain Yawar\OneDrive\Desktop\SQL-Data-Analysis-Project-3\Dataset\Cleaned_Data_project_1.csv")
df.head()

,order_id,date,customer_id,product,quantity,unit_price,shipping_address,payment_method,order_status,tracking_number,items_in_cart,coupon_code,referral_source,total_price
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [14]:
!pip install pandas openpyxl sqlalchemy pymysql

Requirement already satisfied: pandas in c:\users\zulkarnain yawar\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: openpyxl in c:\users\zulkarnain yawar\appdata\local\programs\python\python310\lib\site-packages (3.1.5)
Requirement already satisfied: sqlalchemy in c:\users\zulkarnain yawar\appdata\local\programs\python\python310\lib\site-packages (2.0.46)
Requirement already satisfied: pymysql in c:\users\zulkarnain yawar\appdata\local\programs\python\python310\lib\site-packages (1.1.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\zulkarnain yawar\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\zulkarnain yawar\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\zulkarnain yawar\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\zulkarnain yawar\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: et-xmlfile in c:\users\zulkarnain yawar\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: greenlet>=1 in c:\users\zulkarnain yawar\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\zulkarnain yawar\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\zulkarnain yawar\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:MyNewPassword123!@localhost/project3"
)

In [17]:
df.to_sql(
    "orders",
    con=engine,
    if_exists="replace",
    index=False
)

1200

In [18]:
pd.read_sql(
    "SELECT * FROM orders LIMIT 5",
    engine
)

,order_id,date,customer_id,product,quantity,unit_price,shipping_address,payment_method,order_status,tracking_number,items_in_cart,coupon_code,referral_source,total_price
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04