In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

In [2]:
df = pd.read_csv(r"C:\Users\Zulkarnain Yawar\Downloads\Dataset for Data Analytics - Sheet1.csv")

In [3]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   object
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: float64(2), int64(2), object(10)
memory usage: 131.4+ KB

In [5]:
df.describe()

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1200.000000  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750     5.485000  1053.968300
std       1.407557   197.177146     2.281983   819.856558
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   186.062500     4.000000   410.520000
50%       3.000000   364.210000     5.000000   823.615000
75%       4.000000   521.570000     7.000000  1578.475000
max       5.000000   699.930000    10.000000  3456.400000

In [6]:
df.shape

(1200, 14)

In [8]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [9]:
df['CouponCode'] = df['CouponCode'].fillna('No Coupon')

In [10]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [11]:
df[df.duplicated()]

Empty DataFrame
Columns: [OrderID, Date, CustomerID, Product, Quantity, UnitPrice, ShippingAddress, PaymentMethod, OrderStatus, TrackingNumber, ItemsInCart, CouponCode, ReferralSource, TotalPrice]
Index: []

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.value_counts()

OrderID    Date        CustomerID  Product  Quantity  UnitPrice  ShippingAddress  PaymentMethod  OrderStatus  TrackingNumber  ItemsInCart  CouponCode  ReferralSource  TotalPrice
ORD201199  2023-06-11  C57502      Tablet   4         560.58     201 Main St      Gift Card      Returned     TRK51116746     6            SAVE10      Referral        2242.32       1
ORD200000  2023-01-04  C72649      Monitor  5         570.62     928 Main St      Debit Card     Shipped      TRK37947903     7            SAVE10      Instagram       2853.10       1
ORD200001  2024-08-23  C75739      Phone    2         151.35     823 Main St      Online         Shipped      TRK91186779     3            SAVE10      Referral        302.70        1
ORD200002  2024-02-27  C81728      Tablet   5         550.68     512 Main St      Credit Card    Cancelled    TRK42903982     8            FREESHIP    Email           2753.40       1
ORD200003  2023-10-15  C33540      Chair    1         273.19     275 Main St      Debit Card     Returned     TRK62788070     5            SAVE10      Facebook        273.19        1
                                                                                                                                                                                    ..
ORD200019  2023-01-23  C14552      Monitor  5         224.00     273 Main St      Cash           Returned     TRK59101365     9            SAVE10      Google          1120.00       1
ORD200020  2023-05-08  C54829      Chair    5         62.51      587 Main St      Cash           Pending      TRK16718651     9            WINTER15    Instagram       312.55        1
ORD200021  2024-11-17  C99023      Monitor  4         342.95     569 Main St      Cash           Delivered    TRK52646983     6            No Coupon   Google          1371.80       1
ORD200022  2023-01-29  C34416      Monitor  2         49.62      633 Main St      Online         Pending      TRK75937350     2            SAVE10      Google          99.24         1
ORD200023  2025-04-09  C42372      Phone    4         273.25     755 Main St      Debit Card     Cancelled    TRK36168083     5            FREESHIP    Referral        1093.00       1
Name: count, Length: 1200, dtype: int64

In [14]:
text_cols = ['Product', 'PaymentMethod', 'OrderStatus', 'ReferralSource', 'ShippingAddress']

df[text_cols] = df[text_cols].apply(lambda x: x.str.strip().str.title())
df['CouponCode'] = df['CouponCode'].str.strip().str.upper()

In [17]:
df['PaymentMethod'].value_counts()

PaymentMethod
Online         258
Cash           246
Credit Card    234
Debit Card     232
Gift Card      230
Name: count, dtype: int64

In [18]:
df['OrderStatus'].value_counts()

OrderStatus
Cancelled    250
Returned     247
Pending      237
Shipped      235
Delivered    231
Name: count, dtype: int64

In [19]:
text_cols = ['Product', 'PaymentMethod', 'OrderStatus', 'ReferralSource']

for col in text_cols:
    print(f"\n{col} unique values:")
    print(df[col].unique())

Product unique values:
['Monitor' 'Phone' 'Tablet' 'Chair' 'Printer' 'Laptop' 'Desk']

PaymentMethod unique values:
['Debit Card' 'Online' 'Credit Card' 'Gift Card' 'Cash']

OrderStatus unique values:
['Shipped' 'Cancelled' 'Returned' 'Delivered' 'Pending']

ReferralSource unique values:
['Instagram' 'Referral' 'Email' 'Facebook' 'Google']

In [20]:
for col in text_cols:
    has_spaces = df[col].str.startswith(' ').any() or df[col].str.endswith(' ').any()
    print(f"{col} - Extra spaces: {has_spaces}")

Product - Extra spaces: False
PaymentMethod - Extra spaces: False
OrderStatus - Extra spaces: False
ReferralSource - Extra spaces: False

In [23]:
print(df['Date'].head(20))
print("\nUnique formats sample:")
print(df['Date'].unique()[:10])
print("\nDtype:", df['Date'].dtype)

0     2023-01-04
1     2024-08-23
2     2024-02-27
3     2023-10-15
4     2025-05-08
5     2023-10-23
6     2025-06-17
7     2023-05-12
8     2025-04-02
9     2023-11-21
10    2023-12-29
11    2024-02-17
12    2024-10-15
13    2023-08-30
14    2023-03-27
15    2023-07-17
16    2023-01-24
17    2024-03-02
18    2025-03-26
19    2023-01-23
Name: Date, dtype: object

Unique formats sample:
['2023-01-04' '2024-08-23' '2024-02-27' '2023-10-15' '2025-05-08'
 '2023-10-23' '2025-06-17' '2023-05-12' '2025-04-02' '2023-11-21']

Dtype: object

In [24]:
df['Date'] = pd.to_datetime(df['Date'])

In [25]:
df['Date'].dtype
df['Date'].head()

0   2023-01-04
1   2024-08-23
2   2024-02-27
3   2023-10-15
4   2025-05-08
Name: Date, dtype: datetime64[ns]

In [26]:
# Kaunse columns numeric hone chahiye
numeric_cols = ['Quantity', 'UnitPrice', 'TotalPrice']

for col in numeric_cols:
    print(f"\n{col}:")
    print(f"Dtype: {df[col].dtype}")
    print(f"Sample: {df[col].head()}")

Quantity:
Dtype: int64
Sample: 0    5
1    2
2    5
3    1
4    4
Name: Quantity, dtype: int64

UnitPrice:
Dtype: float64
Sample: 0    570.62
1    151.35
2    550.68
3    273.19
4    626.01
Name: UnitPrice, dtype: float64

TotalPrice:
Dtype: float64
Sample: 0    2853.10
1     302.70
2    2753.40
3     273.19
4    2504.04
Name: TotalPrice, dtype: float64

In [29]:
print("IMPOSSIBLE VALUES SUMMARY")
print(f"Negative Quantity:  {len(df[df['Quantity'] <= 0])}")
print(f"Negative UnitPrice: {len(df[df['UnitPrice'] <= 0])}")
print(f"Negative TotalPrice:{len(df[df['TotalPrice'] <= 0])}")

IMPOSSIBLE VALUES SUMMARY
Negative Quantity:  0
Negative UnitPrice: 0
Negative TotalPrice:0

In [30]:
df.columns.tolist()

['OrderID',
 'Date',
 'CustomerID',
 'Product',
 'Quantity',
 'UnitPrice',
 'ShippingAddress',
 'PaymentMethod',
 'OrderStatus',
 'TrackingNumber',
 'ItemsInCart',
 'CouponCode',
 'ReferralSource',
 'TotalPrice']

In [32]:
def camel_to_snake(name):
    # CamelCase → snake_case
    s = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s).lower()

df.columns = [camel_to_snake(col) for col in df.columns]

In [33]:
df.columns.tolist()

['order_id',
 'date',
 'customer_id',
 'product',
 'quantity',
 'unit_price',
 'shipping_address',
 'payment_method',
 'order_status',
 'tracking_number',
 'items_in_cart',
 'coupon_code',
 'referral_source',
 'total_price']

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1200 non-null   object
 1   date              1200 non-null   datetime64[ns]
 2   customer_id       1200 non-null   object
 3   product           1200 non-null   object
 4   quantity          1200 non-null   int64
 5   unit_price        1200 non-null   float64
 6   shipping_address  1200 non-null   object
 7   payment_method    1200 non-null   object
 8   order_status      1200 non-null   object
 9   tracking_number   1200 non-null   object
 10  items_in_cart     1200 non-null   int64
 11  coupon_code       1200 non-null   object
 12  referral_source   1200 non-null   object
 13  total_price       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [35]:
df.duplicated().sum()

np.int64(0)

In [36]:
df.isnull().sum()

order_id            0
date                0
customer_id         0
product             0
quantity            0
unit_price          0
shipping_address    0
payment_method      0
order_status        0
tracking_number     0
items_in_cart       0
coupon_code         0
referral_source     0
total_price         0
dtype: int64

In [37]:
df.to_csv("cleaned_data.csv", index=False)